SELECT
CASE WHEN Q < '04-01' THEN "1Q"
WHEN Q < '07-01' THEN "2Q"
WHEN Q < '10-01' THEN "3Q"
ELSE "4Q"
END AS QUARTER,
COUNT(ID) AS ECOLI_COUNT

FROM
(
SELECT
ID,
DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') AS Q
FROM ECOLI_DATA
) A 

GROUP BY QUARTER
ORDER BY QUARTER ASC