-- 코드를 작성해주세요
SELECT
SUM(FISH_COUNT) AS FISH_COUNT
FROM (
SELECT
    COUNT(ID) AS FISH_COUNT
FROM FISH_INFO I
LEFT JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE

WHERE N.FISH_NAME IN ('BASS','SNAPPER')
GROUP BY N.FISH_NAME
) A
