SELECT
SUM(SCORE) AS SCORE,
E.EMP_NO,
E.EMP_NAME,
E.POSITION,
E.EMAIL
FROM HR_GRADE G
LEFT JOIN HR_EMPLOYEES E
ON G.EMP_NO = E.EMP_NO
LEFT JOIN HR_DEPARTMENT D
ON D.DEPT_ID = E.DEPT_ID
 
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1